### ISSUE TITLE
Why call it react-

### ISSUE THREAD

**Issue by natew** [radubrehar/react-style-normalizer#1]
Why not just style-normalizer? I love react as much as the next guy, but this one could easily be used anywhere.

Awesome work btw on this. I just added it to reapp.

**Comment by radubrehar** [comment]
You're right Nate :) But document.body.style.webkitTransform is the DOM style name, while React expects WebkitTransform.
Also, this was born when I was working with React. Initially I used https://github.com/nmn/react-stylePrefixr, but it was missing features (prefix both prop name & value if necessary), so I built this for my React needs.

We're using it as well on our React UI kit (see https://github.com/zippyui; if you're insterested, we also have an increasingly popular data grid http://zippyui.github.io/react-datagrid)

Congrats for http://reapp.io/! It seems we are intersecting, at least partly, on React Components. Great job!

**Comment by radubrehar** [comment]
One issue we're still not ok with using inline styles and prefixing them is that when you want your app to be isomorphic, and render server side, and then have React bootstrap your app on the client, it shows a warning and it needs to re-render the app, since style prefixing makes the server and client output differ.

**Comment by natew** [comment]
Yea I noticed that afterwards. You have some nice stuff going, would be nice to see some demos. I like what you've done in some areas, not as much in others. But all is good, Reapp is moving more towards helping people build apps quickly rather than being a component store, we just want to get theming and API nice for the most part.

For example, you only ever pass in one styles prop. You can override any conditional state from there if you want.  You can also selectively style any inner tag. For a button:

```
styles={{
  active: {  ... }

  // override styles the inner div in the button
  inner: { ... }
}}
```

You can also globally override styles when loading a theme, and the override specific things on that. Or even override the base constants (color scheme basically) and then load  theme, and then override global styles on that theme. It's extremely flexible, and lets you do stuff like have a custom color scheme for iOS and Android, but load different styles for each.

**Comment by radubrehar** [comment]
Yes, we have different approaches in some areas. But theming and overriding a theme styles look similar in some areas to our button - see https://www.npmjs.com/package/react-button, and http://zippyui.github.io/react-dropdown-button/ for a demo.

For example, you can override the default button theme
```jsx
var themes = require('react-button').themes
assign(themes.default.style, {
    color: 'red'
})
```

It's also interesting to see how @petehunt is progressing with https://github.com/petehunt/jsxstyle

Other demos:
http://zippyui.github.io/react-date-picker/
http://zippyui.github.io/react-time-picker/
http://zippyui.github.io/react-datagrid/#/examples/column-resizing
http://zippyui.github.io/react-split-button/ (here you can also see the https://www.npmjs.com/package/react-menus package at work, opening under the split button)
http://zippyui.github.io/react-radio/
and releasing soon: window, messagebox, tabpanel, splitcontainer, listview, inputfield, datefield, combobox, etc.

Very nice work on reapp! And the design is very nice. We still need the touch of a designer on ZippyUI :)
