### ISSUE TITLE
Deep nesting not respected

### ISSUE THREAD

**Issue by tquetano-r7** [radubrehar/react-style-normalizer#3]
I was trying to use this (absolutely wonderful) prefixer on nested objects, and noticed it wasn't applying to nested objects. Would it be possible to make that change? I'm going to try to fiddle with it to submit a pull request, but I imagine its just a matter of recursively calling the function if the value of the key-value pair is an object.

**Comment by tquetano-r7** [comment]
So forgive the newness to github, but it doesn't seem that I'm allowed to create a branch to submit pull requests with, so I'll just plop the code in here.

```
function normalize(key, value){

	var result = plugins(key, value)

	return map(function(result){
		if(typeof result.value === "object" && !!result.value) {
			for(var nestedKey in result.value) {
				var tempVal = normalize(nestedKey, result.value[nestedKey]);
				// kill the old one just in case it was the non-prefixed key
				delete result.value[nestedKey];
				// assign value new key/value pair to result.value
				result.value[tempVal.key] = tempVal.value;
			}
		}

		return {
			key  : getPrefixed(result.key, result.value),
			value: result.value
		}
	}, result)

	return result
}
```

I'm certain there is a more eloquent way to do it, I just did something quick and dirty. Seems to do the job:

```
console.log(recess.prefix({
    test:{
        really:{
            deep:{
                nesting:{
                    userSelect:"none"
                }
            }
        }
    }
}));
// {WebkitUserSelect: "none"}
```

I know you haven't touched this library in a bit, but it would be awesome if you could integrate it in so I could use the standard NPM. Thanks!

**Comment by radubrehar** [comment]
Thanks for your genuine interest in this. Supporting nested styles is out of scope for this project. If you want to have this, you could use other npm modules and then pass the resulting object to the prefixer.

You might find https://www.npmjs.com/package/to-style useful.

**Comment by tquetano-r7** [comment]
It's cool, I actually put my own prefixing module together. It's intentionally simple as a starting point, but gets the job done for now.

https://www.npmjs.com/package/react-prefixer, if you're interested.
